#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpCalBgoMip, 2014-09-24 17:19:01 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpBgoMip as DmpBgoMip

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.Set("FromEvent","500")
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Warning")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc options
DMPSW.RootIOSvc.Set("Input/FileName","DmpRawData.root")
#DMPSW.RootIOSvc.Set("Output/FileName","./DmpCalBgoMip.root")
DMPSW.RootIOSvc.Set("Output/WriteList","Calibration/Bgo/Mip")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
calBgoMip = DmpBgoMip.DmpAlgBgoMip()
DMPSW.AlgMgr.Append(calBgoMip)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

