#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpCalBgoMip, 2014-09-24 17:19:01 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpBgoMip as DmpBgoMip

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.MaxEventNumber(4)     # default: -1
#DMPSW.Core.StartTime("2013-01-01 00:00:00")     # default: 2013-01-01 00:00:00
#DMPSW.Core.StopTime("2016-01-01 00:00:00")      # default: 2053-01-01 00:00:00
#DMPSW.Core.LogLevel("Debug")      # Value = {Error | Warning | Info | Debug}. default: Info.
#DMPSW.Core.LogHeader("On") # default: off

#-------------------------------------------------------------------
# RootIOSvc options
DMPSW.RootIOSvc.InputFile("DmpRawData.root")
#DMPSW.RootIOSvc.OutputFile("./DmpCalBgoMip.root")
DMPSW.RootIOSvc.WriteList("Calibration/Bgo")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
calBgoMip = DmpBgoMip.DmpAlgBgoMip()
DMPSW.AlgMgr.Append(calBgoMip)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

